import React, {useState} from 'react';
import {Routes, Route, Link, useNavigate, useParams} from 'react-router-dom';
import {Search, MapPin, Heart, User, Home, SlidersHorizontal, BedDouble, Bath, Maximize, ArrowLeft, CheckCircle2} from 'lucide-react';
import {MapContainer, TileLayer, Marker, Popup} from 'react-leaflet';
import L from 'leaflet';

const properties = [
 {id:1,title:'Modern 2 BHK Apartment',city:'Hyderabad',area:'Kondapur',price:6200000,beds:2,baths:2,size:1180,type:'Apartment',lat:17.458,lon:78.377,tag:'Verified',desc:'Bright, semi-furnished apartment close to offices, cafés and public transport.',amenities:['Parking','Power Backup','Gym','Security']},
 {id:2,title:'Premium 3 BHK Family Home',city:'Hyderabad',area:'Gachibowli',price:9400000,beds:3,baths:3,size:1650,type:'Apartment',lat:17.440,lon:78.348,tag:'Featured',desc:'Spacious family home with excellent natural light and community amenities.',amenities:['Club House','Parking','Lift','Security']},
 {id:3,title:'Cozy 1 BHK Studio',city:'Bengaluru',area:'Whitefield',price:3900000,beds:1,baths:1,size:720,type:'Apartment',lat:12.969,lon:77.750,tag:'Verified',desc:'Compact and efficient home ideal for young professionals and investors.',amenities:['Gym','Lift','CCTV','Power Backup']},
 {id:4,title:'Independent Villa with Garden',city:'Pune',area:'Baner',price:12800000,beds:4,baths:4,size:2400,type:'Villa',lat:18.560,lon:73.786,tag:'New',desc:'Independent villa with private garden, parking and a quiet residential setting.',amenities:['Garden','Parking','Security','Terrace']}
];
const icon = new L.Icon({iconUrl:'https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon.png',iconRetinaUrl:'https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon-2x.png',shadowUrl:'https://unpkg.com/leaflet@1.9.4/dist/images/marker-shadow.png',iconSize:[25,41],iconAnchor:[12,41]});
function Header(){return <header className="header"><Link to="/" className="brand"><span className="brandMark">N</span>NestFinder</Link><nav><Link to="/search">Find a Home</Link><Link to="/dashboard">My Dashboard</Link></nav><div className="headerActions"><Link to="/login" className="login">Log in</Link><Link to="/signup" className="btn small">Sign up</Link></div></header>}
function Landing(){const [q,setQ]=useState('');const nav=useNavigate();return <><Header/><main><section className="hero"><div className="heroCopy"><div className="eyebrow">SMARTER PROPERTY SEARCH</div><h1>Find a place you’ll <span>love to live.</span></h1><p>Search verified homes, compare properties and explore locations on an interactive map.</p><div className="searchBox"><Search size={20}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="City, neighbourhood or property type"/><button onClick={()=>nav('/search?q='+encodeURIComponent(q))}>Search</button></div><div className="quick"><span>Popular:</span><button onClick={()=>nav('/search?q=Hyderabad')}>Hyderabad</button><button onClick={()=>nav('/search?q=Bengaluru')}>Bengaluru</button><button onClick={()=>nav('/search?q=Pune')}>Pune</button></div></div><div className="heroCard"><div className="mockImage"><Home size={56}/></div><div className="heroCardBody"><div><b>Modern 2 BHK Apartment</b><small>Kondapur, Hyderabad</small></div><strong>₹62 L</strong></div></div></section><section className="features"><div><span>01</span><h3>Verified listings</h3><p>Clear property information so you can search with confidence.</p></div><div><span>02</span><h3>Map-first discovery</h3><p>See homes around your preferred neighbourhood and commute.</p></div><div><span>03</span><h3>Personal dashboard</h3><p>Save favourites and keep your preferences in one place.</p></div></section><section className="cta"><div><h2>Ready to find your next home?</h2><p>Create an account and start saving properties.</p></div><Link className="btn" to="/signup">Create free account</Link></section></main></>}
function PropertyCard({p}){const [fav,setFav]=useState(false);return <article className="propertyCard"><div className="propertyImage"><span className="tag">{p.tag}</span><button className={'heart '+(fav?'active':'')} onClick={()=>setFav(!fav)}><Heart size={19} fill={fav?'currentColor':'none'}/></button><Home size={48}/></div><div className="propertyBody"><div className="row"><div><h3>{p.title}</h3><p><MapPin size={14}/>{p.area}, {p.city}</p></div><b>₹{(p.price/100000).toFixed(0)} L</b></div><div className="stats"><span><BedDouble/> {p.beds} Beds</span><span><Bath/> {p.baths} Baths</span><span><Maximize/> {p.size} sq.ft</span></div><Link className="outline" to={'/property/'+p.id}>View details</Link></div></article>}
function SearchPage(){const params=new URLSearchParams(location.search);const [q,setQ]=useState(params.get('q')||'');const [filter,setFilter]=useState('All');const filtered=properties.filter(p=>(filter==='All'||p.type===filter)&&(!q||(`${p.city} ${p.area} ${p.title}`.toLowerCase().includes(q.toLowerCase()))));return <><Header/><main className="searchPage"><div className="searchTop"><div><div className="eyebrow">PROPERTY SEARCH</div><h1>Explore homes</h1><p>{filtered.length} properties matching your search</p></div><div className="searchBar"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search location..."/><SlidersHorizontal/><select value={filter} onChange={e=>setFilter(e.target.value)}><option>All</option><option>Apartment</option><option>Villa</option></select></div></div><div className="resultsLayout"><section className="results">{filtered.map(p=><PropertyCard key={p.id} p={p}/>)}</section><section className="map"><MapContainer center={[17.43,78.40]} zoom={5} scrollWheelZoom={false}><TileLayer attribution='&copy; OpenStreetMap contributors' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/>{filtered.map(p=><Marker key={p.id} position={[p.lat,p.lon]} icon={icon}><Popup><b>{p.title}</b><br/>₹{(p.price/100000).toFixed(0)} L</Popup></Marker>)}</MapContainer></section></div></main></>}
function PropertyDetail(){const {id}=useParams();const p=properties.find(x=>x.id===Number(id))||properties[0];return <><Header/><main className="detail"><Link to="/search" className="back"><ArrowLeft size={17}/> Back to search</Link><div className="detailGrid"><div><div className="detailImage"><Home size={80}/></div><div className="detailFacts"><span><BedDouble/> {p.beds} Bedrooms</span><span><Bath/> {p.baths} Bathrooms</span><span><Maximize/> {p.size} sq.ft</span></div><h2>About this property</h2><p className="desc">{p.desc}</p><h2>Amenities</h2><div className="amenities">{p.amenities.map(a=><span key={a}><CheckCircle2/> {a}</span>)}</div></div><aside className="contactCard"><span className="tag">{p.tag}</span><h1>{p.title}</h1><p><MapPin/> {p.area}, {p.city}</p><div className="bigPrice">₹{(p.price/100000).toFixed(0)} L</div><button className="btn full">Contact owner</button><button className="outline full">Save property</button><small>Response usually within 24 hours</small></aside></div></main></>}
function FormPage({signup=false}){const nav=useNavigate();return <><Header/><main className="formWrap"><form className="formCard" onSubmit={e=>{e.preventDefault();nav('/dashboard')}}><div className="brand center"><span className="brandMark">N</span>NestFinder</div><h1>{signup?'Create your account':'Welcome back'}</h1><p>{signup?'Save properties and personalise your search.':'Log in to manage your saved properties.'}</p>{signup&&<label>Full name<input required placeholder="Your name"/></label>}<label>Email<input required type="email" placeholder="you@example.com"/></label><label>Password<input required type="password" placeholder="••••••••"/></label>{signup&&<label>Preferred city<input placeholder="e.g. Hyderabad"/></label>}<button className="btn full">{signup?'Create account':'Log in'}</button><small className="centerText">{signup?'Already have an account? ':'New to NestFinder? '}<Link to={signup?'/login':'/signup'}>{signup?'Log in':'Create an account'}</Link></small></form></main></>}
function Dashboard(){return <><Header/><main className="dashboard"><div className="dashHead"><div><div className="eyebrow">MY DASHBOARD</div><h1>Hello, Sanjeev 👋</h1><p>Manage your saved homes and search preferences.</p></div><Link className="btn" to="/search">Explore properties</Link></div><div className="dashGrid"><section className="panel"><h2>Search preferences</h2><label>Preferred city<input defaultValue="Hyderabad"/></label><label>Property type<select defaultValue="Apartment"><option>Apartment</option><option>Villa</option><option>Any</option></select></label><label>Budget<input defaultValue="₹40 L – ₹1 Cr"/></label><button className="btn">Save preferences</button></section><section className="panel"><div className="panelTitle"><h2>Saved properties</h2><Link to="/search">View all</Link></div>{properties.slice(0,3).map(p=><div className="saved" key={p.id}><div className="savedImg"><Home/></div><div><b>{p.title}</b><small>{p.area}, {p.city}</small><strong>₹{(p.price/100000).toFixed(0)} L</strong></div><Heart size={18}/></div>)}</section></div></main></>}
export default function App(){return <Routes><Route path="/" element={<Landing/>}/><Route path="/search" element={<SearchPage/>}/><Route path="/property/:id" element={<PropertyDetail/>}/><Route path="/login" element={<FormPage/>}/><Route path="/signup" element={<FormPage signup/>}/><Route path="/dashboard" element={<Dashboard/>}/></Routes>}
